### ISSUE TITLE
Search by field doesn't work

### ISSUE THREAD

**Issue by bigsmile01** [hssm/advanced-browser#41] opened 2019-01-09 18:05 UTC
Anki documentation says the following:

**front:*
find notes that have a Front field, empty or not**

This works perfectly when Advanced-browser is NOT enabled. But the moment I enable Advanced-browser, this form of searching stops working (It just displays no result). In fact, once you conduct the above search, all searching (including browsing decks) stops working until Anki is restarted.

Any ideas? Thanks!

**Comment by hssm** [comment] 2019-01-20 18:08
I can't reproduce this. The last sentence seems strange and makes it sound like another case of #14. Are you using a Mac?

**Comment by bigsmile01** [comment] 2019-01-20 18:38
Yes, I am using a Mac. 

It is similar to #14, except in #14 none of the searches work at all. 
In my case, regular searches work perfectly. The issue only occurs if I do I special search such as "Front:". (However, as noted in the OP, if I do a special search, then all searches will stop working until Anki is restarted).

**Comment by hssm** [comment] 2019-01-21 15:08
I'm afraid I don't have any ideas on how to progress with this issue without more details. If you are able to get a console log output when the error occurs it might have some useful details.

Do your field names have any punctuation or non-alphanumeric values? After you trigger the bug, what happens if you sort by a different column?

**Comment by bigsmile01** [comment] 2019-01-24 15:59
> Do your field names have any punctuation or non-alphanumeric values?

Some of my fields have dashes E.g. English-Original


> After you trigger the bug, what happens if you sort by a different column?
If I sort by a different column, that seems to get it working again!! I guess that can be used as a workaround for now. 

> If you are able to get a console log output when the error occurs it might have some useful details.

Here it is: 

```
default	15:53:31.384412 +0000	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      previouslyRunningApps: (
        {
        BackgroundState = 2;
        BundleID = "com.google.chrome";
        Hide = 0;
        Path = "/Applications/Google Chrome.app";
    },
        {
        BackgroundState = 2;
        BundleID = "net.ichi2.anki";
        Hide = 0;
        Path = "/Applications/Anki.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.itunes";
        Hide = 0;
        Path = "/Applications/iTunes.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.notes";
        Hide = 0;
        Path = "/Applications/Notes.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.ical";
        Hide = 0;
        Path = "/Applications/Calendar.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.reminders";
        Hide = 0;
        Path = "/Applications/Reminders.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.overdrive.overdrivemediaconsole";
        Hide = 0;
        Path = "/Applications/OverDrive Media Console.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.systempreferences";
        Hide = 0;
        Path = "/Applications/System Preferences.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.finder";
        Hide = 0;
        Path = "/System/Library/CoreServices/Finder.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.preview";
        Hide = 0;
        Path = "/Applications/Preview.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.adobe.photoshop";
        Hide = 0;
        Path = "/Applications/Adobe Photoshop CS6/Adobe Photoshop CS6.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.iwork.pages";
        Hide = 0;
        Path = "/Applications/Pages.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.adobe.acrobat.pro";
        Hide = 0;
        Path = "/Applications/Adobe Acrobat X Pro/Adobe Acrobat Pro.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.safari";
        Hide = 0;
        Path = "/Applications/Safari.app";
    },
        {
        BackgroundState = 2;
        BundleID = "de.wetfish.speed-up";
        Hide = 0;
        Path = "/Applications/Speed-Up.app";
    },
        {
        BackgroundState = 3;
        BundleID = "com.iospirit.remotebuddy";
        Hide = 0;
        Path = "/Applications/Remote Buddy.app";
    }
)
default	15:53:31.389849 +0000	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      checkAgainstApp is : Anki
default	15:53:31.389867 +0000	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] | entered. checking app: Anki
default	15:53:31.389898 +0000	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Adding to relaunchArray: Anki
default	15:53:31.402613 +0000	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Contents:(
        {
        BackgroundState = 2;
        BundleID = "com.apple.console";
        Hide = 0;
        Path = "/Applications/Utilities/Console.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.google.chrome";
        Hide = 0;
        Path = "/Applications/Google Chrome.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.notes";
        Hide = 0;
        Path = "/Applications/Notes.app";
    },
        {
        BackgroundState = 2;
        BundleID = "net.ichi2.anki";
        Hide = 0;
        Path = "/Applications/Anki.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.itunes";
        Hide = 0;
        Path = "/Applications/iTunes.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.ical";
        Hide = 0;
        Path = "/Applications/Calendar.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.reminders";
        Hide = 0;
        Path = "/Applications/Reminders.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.overdrive.overdrivemediaconsole";
        Hide = 0;
        Path = "/Applications/OverDrive Media Console.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.systempreferences";
        Hide = 0;
        Path = "/Applications/System Preferences.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.finder";
        Hide = 0;
        Path = "/System/Library/CoreServices/Finder.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.preview";
        Hide = 0;
        Path = "/Applications/Preview.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.adobe.photoshop";
        Hide = 0;
        Path = "/Applications/Adobe Photoshop CS6/Adobe Photoshop CS6.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.iwork.pages";
        Hide = 0;
        Path = "/Applications/Pages.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.adobe.acrobat.pro";
        Hide = 0;
        Path = "/Applications/Adobe Acrobat X Pro/Adobe Acrobat Pro.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.safari";
        Hide = 0;
        Path = "/Applications/Safari.app";
    },
        {
        BackgroundState = 2;
        BundleID = "de.wetfish.speed-up";
        Hide = 0;
        Path = "/Applications/Speed-Up.app";
    },
        {
        BackgroundState = 3;
        BundleID = "com.iospirit.remotebuddy";
        Hide = 0;
        Path = "/Applications/Remote Buddy.app";
    }
)
default	15:53:45.391007 +0000	Anki	TEMP SORT TABLE PATH
default	15:53:45.391064 +0000	Anki	Temp sort table sql:  create temp table tmp as select *, (select valueForField(mid, flds, 'Order') from notes where id = c.nid) as srt from cards c, notes n where c.nid=n.id and ((n.tags like ?) and ((n.mid = 1423246462293 and c.ord = 0) or (n.mid = 1523100273664 and c.ord = 0) or (n.mid = 1536232726764 and c.ord = 0)))
default	15:53:45.434812 +0000	Anki	sql :
default	15:53:45.434872 +0000	Anki	select id, srt from tmp order by tmp.srt is null, tmp.srt is '',
default	15:53:45.434896 +0000	Anki	case when tmp.srt glob '*[^0-9.]*' then tmp.srt else cast(tmp.srt AS real) end
default	15:53:45.434916 +0000	Anki	collate nocase
default	15:53:45.437842 +0000	Anki	Search took: 46ms
default	15:53:47.567950 +0000	Anki	TEMP SORT TABLE PATH
default	15:53:47.568007 +0000	Anki	Temp sort table sql:  create temp table tmp as select *, (select valueForField(mid, flds, 'Order') from notes where id = c.nid) as srt from cards c where ((c.queue = -1))
default	15:53:47.572154 +0000	Anki	sql :
default	15:53:47.572224 +0000	Anki	select id, srt from tmp order by tmp.srt is null, tmp.srt is '',
default	15:53:47.572255 +0000	Anki	case when tmp.srt glob '*[^0-9.]*' then tmp.srt else cast(tmp.srt AS real) end
default	15:53:47.572282 +0000	Anki	collate nocase
default	15:53:47.572311 +0000	Anki	Search took: 4ms
default	15:53:56.513604 +0000	Anki	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 0 vs 307, 513, <private>
default	15:54:12.415071 +0000	Anki	TEMP SORT TABLE PATH
default	15:54:12.415125 +0000	Anki	Temp sort table sql:  create temp table tmp as select *, (select valueForField(mid, flds, 'Order') from notes where id = c.nid) as srt from cards c, notes n where c.nid=n.id and ((c.did in (1462036506232) or c.odid in (1462036506232)) and ((n.mid = 1423246462293 and c.ord = 0) or (n.mid = 1523100273664 and c.ord = 0) or (n.mid = 1536232726764 and c.ord = 0)) and (n.tags like ?))
default	15:54:12.447289 +0000	Anki	sql :
default	15:54:12.447359 +0000	Anki	select id, srt from tmp order by tmp.srt is null, tmp.srt is '',
default	15:54:12.447383 +0000	Anki	case when tmp.srt glob '*[^0-9.]*' then tmp.srt else cast(tmp.srt AS real) end
default	15:54:12.447403 +0000	Anki	collate nocase
default	15:54:12.447425 +0000	Anki	Search took: 32ms
default	15:54:14.068807 +0000	Anki	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 0 vs 309, 513, <private>
default	15:54:37.636256 +0000	Anki	TEMP SORT TABLE PATH
default	15:54:37.636316 +0000	Anki	Temp sort table sql:  create temp table tmp as select *, (select valueForField(mid, flds, 'Order') from notes where id = c.nid) as srt from cards c where ((c.did in (1541002979450) or c.odid in (1541002979450)))
default	15:54:37.664647 +0000	Anki	sql :
default	15:54:37.664714 +0000	Anki	select id, srt from tmp order by tmp.srt is null, tmp.srt is '',
default	15:54:37.664738 +0000	Anki	case when tmp.srt glob '*[^0-9.]*' then tmp.srt else cast(tmp.srt AS real) end
default	15:54:37.664758 +0000	Anki	collate nocase
default	15:54:37.667472 +0000	Anki	Search took: 31ms
default	15:54:38.179999 +0000	Anki	TEMP SORT TABLE PATH
default	15:54:38.180062 +0000	Anki	Temp sort table sql:  create temp table tmp as select *, (select valueForField(mid, flds, 'Order') from notes where id = c.nid) as srt from cards c where ((c.did in (1487342289357) or c.odid in (1487342289357)))
default	15:54:38.190599 +0000	Anki	sql :
default	15:54:38.190656 +0000	Anki	select id, srt from tmp order by tmp.srt is null, tmp.srt is '',
default	15:54:38.190685 +0000	Anki	case when tmp.srt glob '*[^0-9.]*' then tmp.srt else cast(tmp.srt AS real) end
default	15:54:38.190710 +0000	Anki	collate nocase
default	15:54:38.190735 +0000	Anki	Search took: 10ms
default	15:54:38.667567 +0000	Anki	TEMP SORT TABLE PATH
default	15:54:38.667614 +0000	Anki	Temp sort table sql:  create temp table tmp as select *, (select valueForField(mid, flds, 'Order') from notes where id = c.nid) as srt from cards c, notes n where c.nid=n.id and ((n.tags like ?) and ((n.mid = 1423246462293 and c.ord = 0) or (n.mid = 1523100273664 and c.ord = 0) or (n.mid = 1536232726764 and c.ord = 0)))
default	15:54:38.696998 +0000	Anki	sql :
default	15:54:38.697063 +0000	Anki	select id, srt from tmp order by tmp.srt is null, tmp.srt is '',
default	15:54:38.697088 +0000	Anki	case when tmp.srt glob '*[^0-9.]*' then tmp.srt else cast(tmp.srt AS real) end
default	15:54:38.697109 +0000	Anki	collate nocase
default	15:54:38.697273 +0000	Anki	Search took: 29ms
default	15:54:39.285693 +0000	Anki	TEMP SORT TABLE PATH
default	15:54:39.285751 +0000	Anki	Temp sort table sql:  create temp table tmp as select *, (select valueForField(mid, flds, 'Order') from notes where id = c.nid) as srt from cards c, notes n where c.nid=n.id and ((n.tags like ?) and ((n.mid = 1423246462293 and c.ord = 0) or (n.mid = 1523100273664 and c.ord = 0) or (n.mid = 1536232726764 and c.ord = 0)))
default	15:54:39.316443 +0000	Anki	sql :
default	15:54:39.316512 +0000	Anki	select id, srt from tmp order by tmp.srt is null, tmp.srt is '',
default	15:54:39.316536 +0000	Anki	case when tmp.srt glob '*[^0-9.]*' then tmp.srt else cast(tmp.srt AS real) end
default	15:54:39.316556 +0000	Anki	collate nocase
default	15:54:39.316719 +0000	Anki	Search took: 31ms
default	15:54:49.571165 +0000	Anki	TEMP SORT TABLE PATH
default	15:54:49.572534 +0000	Anki	Temp sort table sql:  create temp table tmp as select *, (select valueForField(mid, flds, 'Order') from notes where id = c.nid) as srt from cards c, notes n where c.nid=n.id and ((n.id in (1322780692343,1322780692344,1322780692345,1322780692346,1322780692347,1322780692348,1322780692349,1322780692350,1322780692351,1322780692352,1322780692353,1322780692354,1322780692355,1322780692356,1322780692357,1322780692358,1322780692359,1322780692360,1322780692361,1322780692362,1322780692363,1322780692364,1322780692365,
default	15:54:49.572586 +0000	Anki	Temp sort table sql:  create temp table tmp as select *, (select valueForField(mid, flds, 'Order') from notes where id = c.nid) as srt from cards c, notes n where c.nid=n.id and ((n.id in (1322780692343,1322780692344,1322780692345,1322780692346,1322780692347,1322780692348,1322780692349,1322780692350,1322780692351,1322780692352,1322780692353,1322780692354,1322780692355,1322780692356,1322780692357,1322780692358,1322780692359,1322780692360,1322780692361,1322780692362,1322780692363,1322780692364,1322780692365,
default	15:54:49.572633 +0000	Anki	Temp sort table sql:  create temp table tmp as select *, (select valueForField(mid, flds, 'Order') from notes where id = c.nid) as srt from cards c, notes n where c.nid=n.id and ((n.id in (1322780692343,1322780692344,1322780692345,1322780692346,1322780692347,1322780692348,1322780692349,1322780692350,1322780692351,1322780692352,1322780692353,1322780692354,1322780692355,1322780692356,1322780692357,1322780692358,1322780692359,1322780692360,1322780692361,1322780692362,1322780692363,1322780692364,1322780692365,
default	15:54:59.547181 +0000	Anki	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 0 vs 311, 513, <private>

```

**Comment by hssm** [comment] 2019-02-24 12:22
Same as #25 and should be fixed now.

**Closed by hssm** 2019-02-24 12:22 UTC
